name: Auto Commit Changes

on:
  push:
    branches:
      - main
  schedule:
    - cron: '50 0 * * *'  # Runs every day at midnight

jobs:
  commit_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Set up Git
        run: |
          git config --global user.name "Satendra Kumar Parteti"
          git config --global user.email "satendrakumarparteti.work@gmail.com"

      - name: Make changes (e.g., add a file, modify a file)
        run: |
          # Example: Create a new file
          echo "New change" >> new_file.txt
          git add .
        
      - name: Commit changes
        run: |
          git commit -m "Auto commit by GitHub Actions"
          git push

      - name: Push changes to the repository
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
