name: Auto Commit Changes

on:
  schedule:
    - cron: '2 1 * * *'  # Runs every day at 01:02 AM UTC

jobs:
  commit_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"

      - name: Check for changes and commit
        run: |
          git add .
          git diff --cached --quiet || git commit -m "Auto commit by GitHub Actions"
        
      - name: Pull remote changes before pushing
        run: |
          git pull origin main --rebase || echo "No changes to pull"
        
      - name: Force push changes to the repository
        run: |
          git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
